import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {analyseM2, parseXStructured, filterXPosts} from '../web-source/m2.js';
const hashes=JSON.parse(fs.readFileSync('source-hashes.json','utf8'));
for(const [file,hash] of Object.entries(hashes)) assert.equal(crypto.createHash('sha256').update(fs.readFileSync('web-source/'+file)).digest('hex'),hash,`Original changed: ${file}`);
const bundle=fs.readFileSync('www/app.js','utf8');
assert(!bundle.includes('cdn.jsdelivr.net'));
assert(!bundle.includes('X_BEARER_TOKEN'));
assert(!bundle.includes('api.x.com'));
assert(!bundle.includes('serviceWorker.register'));
assert(bundle.includes('CapacitorHttp.get'));
assert(bundle.includes('Share.share'));
assert(bundle.includes('Clipboard.read'));
assert(!fs.existsSync('www/netlify'));
const config=JSON.parse(fs.readFileSync('capacitor.config.json','utf8'));
assert.equal(config.appId,'com.veriodetect.app');
assert.equal(config.server?.url,undefined);
assert(!fs.readFileSync('ios/App/CapApp-SPM/Package.swift','utf8').includes('\\'));
const posts=[0,2,19,83,92,211,890,910].map((m,i)=>({time:1700000000000+m*60000,text:`Post ${i}`,type:'original'}));
const forward=analyseM2(posts), backward=analyseM2([...posts].reverse());
assert.deepEqual(backward,forward,'M2 must preserve the v0.7.6 chronological-order fix');
assert.equal(forward.diagnostics.positiveIntervals,7);
assert(forward.diagnostics.cv>0);
assert.throws(()=>analyseM2(posts.map(p=>({...p,time:posts[0].time}))),/Timestamp integrity/);
const parsed=parseXStructured({data:[{id:'1',created_at:'2026-01-01T12:00:00Z',text:'first'},{id:'2',created_at:'2026-01-02T12:00:00Z',text:'reply',referenced_tweets:[{type:'replied_to'}]}]});
assert.equal(filterXPosts(parsed,'originals').length,1);
assert.equal(filterXPosts(parsed,'replies').length,1);
console.log('PASS: original source hashes, client/backend separation, native integration, chronological M2 regression and activity filters.');
// Exercise the compiled API adapter against native HTTP reply shapes.
const apiSource=bundle.slice(bundle.indexOf('async function apiJSON('),bundle.indexOf('async function checkXConnection('));
assert(apiSource.startsWith('async function apiJSON('));
let reply,request;
const api=new Function('CapacitorHttp',apiSource+'; return apiJSON;')({get:async options=>{request=options;return reply;}});
reply={status:200,data:{posts:[{id:'1'}]}};
assert.deepEqual(await api('/api/x-posts?username=example&count=100'),reply.data);
assert.equal(new URL(request.url).pathname,'/api/x-posts');
assert.equal(new URL(request.url).searchParams.get('count'),'100');
assert.equal(new URL(request.url).protocol,'https:');
reply={status:200,data:'{"ok":true}'};
assert.deepEqual(await api('/api/x-status'),{ok:true});
reply={status:429,data:{error:'X API rate/usage limit reached (HTTP 429).'}};
await assert.rejects(api('/api/x-status'),/429/);
reply={status:200,data:'<!doctype html>'};
await assert.rejects(api('/api/x-status'),/instead of JSON/);
console.log('PASS: compiled native API adapter: URL routing, object/text JSON, rate limits and non-JSON errors.');
